### ISSUE TITLE
Dont prevent startup if login authentication fails

### ISSUE THREAD

**Issue by RAnders00** [pajlada/pajbot2#23]
Currently, if the bot fails to authenticate one of the bot accounts, the process aborts during the startup. It would be benefitial to start the bot, just not connected to those accounts and the associated bot channels, so one can use the web to re-authenticate that bot account.

**Comment by pajlada** [comment]
Big issues fixed in 3c61b9656e75c8279191d9211357dd970f701682

still some work to be done with refresh tokens etc, but at least you can use the proper web auth page now since the bot still runs

on /admin you can see if the login failed or not by checking the "Connected" state
